import { prisma } from "@/lib/prisma";

const SELLERS = [
  {
    id: "seller-1",
    clerkId: "clerk_seller_1",
    name: "Nike Official Store",
    email: "contact@nike.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=200",
    description:
      "Tienda oficial de Nike con zapatillas, ropa deportiva y accesorios originales.",
  },
  {
    id: "seller-2",
    clerkId: "clerk_seller_2",
    name: "Adidas Store",
    email: "contact@adidas.com",
    avatarUrl:
      "https://images.unsplash.com/photo-1518002171953-a080ee817e1f?q=80&w=200",
    description:
      "Store oficial de Adidas especializada en calzado urbano, running y entrenamiento.",
  },
];

const PRODUCTS = [
  {
    id: "1",
    name: "Nike Vomero Premium",
    price: 449999,
    brand: "nike",
    image: "/images/nike.jpg",
    description: "Zapatilla deportiva de alta calidad ideal para uso diario y rendimiento.",
    direction: "Soller 155, Buenos Aires",
    category: "mujer",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Blanco", "Negro", "Rosa"],
    sellerId: "seller-1",
  },
  {
    id: "2",
    name: "Adizero Adios PRO 4",
    price: 419999,
    brand: "adidas",
    image: "/images/adidas.jpg",
    description: "Zapatilla de running de alto rendimiento diseñada para corredores serios.",
    direction: "Cramer 165, Buenos Aires",
    category: "mujer",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Blanco", "Azul", "Negro"],
    sellerId: "seller-2",
  },
  {
    id: "3",
    name: "Nike Dunk Low Retro",
    price: 249999,
    brand: "nike",
    image: "/images/nike-dunk.jpg",
    description: "Zapatilla icónica de estilo urbano con diseño retro y comodidad moderna.",
    direction: "Palermo 200, Buenos Aires", 
    category: "hombre",
    sizes: [40, 41, 42, 43, 44, 45],
    colors: ["Blanco", "Negro", "Rojo"],
    sellerId: "seller-1",
  },
  {
    id: "4",
    name: "Air Jordan 1 Mid SE",
    price: 429999,
    brand: "nike",
    image: "/images/nike-air.jpg",
    description: "Zapatilla urbana clásica con diseño moderno y detalles premium.",
    direction: "San Cristobal 155, Buenos Aires",
    category: "mujer",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Blanco", "Negro", "Dorado"],
    sellerId: "seller-1",
  },
  {
    id: "5",
    name: "Air Jordan 1 Mid SE",
    price: 132999,
    brand: "nike",
    image: "/images/nike-gt.jpg",
    description: "Zapatilla de baloncesto clásica con diseño moderno y detalles premium.",
    direction: "Moreno 76, Buenos Aires",
    category: "nino",
    sizes: [28, 29, 30, 31, 32, 33],
    colors: ["Rojo", "Blanco", "Negro"],
    sellerId: "seller-1",
  },
  {
    id: "6",
    name: "Adizero Drive RC",
    price: 132999,
    brand: "adidas",
    image: "/images/adidas-pro.jpg",
    description: "Zapatilla de running ligera y reactiva diseñada para corredores de nivel intermedio.",
    direction: "Cramer 99, Buenos Aires",
    category: "mujer",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Blanco", "Azul", "Rosado"],
    sellerId: "seller-2",
  },
  {
    id: "7",
    name: "Adizero Adios PRO 4",
    price: 419999,
    brand: "adidas",
    image: "/images/adidas-proh.jpg",
    description: "Zapatilla de running de alto rendimiento diseñada para corredores serios.",
    direction: "Chacros 165, Buenos Aires",
    category: "hombre",
    sizes: [40, 41, 42, 43, 44, 45],
    colors: ["Negro", "Gris", "Blanco"],
    sellerId: "seller-2",
  },
  {
    id: "8",
    name: "Campus 00s Comfort Closure con Cordones Elásticos",
    price: 419999,
    brand: "adidas",
    image: "/images/adidas-child.jpg",
    description: "Zapatilla urbana de estilo retro con cierre de cordones elásticos para niños.",
    direction: "San Juan 165, Buenos Aires",
    category: "nino",
    sizes: [28, 29, 30, 31, 32, 33],
    colors: ["Blanco", "Azul", "Verde"],
    sellerId: "seller-2",
  },
    {
    id: "9",
    name: "Nike Air Force 1 Low",
    price: 379999,
    brand: "nike",
    image: "/images/air-force-1.jpg",
    description: "Ícono urbano clásico de Nike.",
    direction: "Av. Santa Fe 1200",
    category: "nino",
    sizes: [34,35],
    colors: ["Blanco", "Negro"],
    sellerId: "seller-1",
  },
  {
    id: "10",
    name: "Nike Air Max 270",
    price: 459999,
    brand: "nike",
    image: "/images/air-max-270.jpg",
    description: "Amortiguación Air visible y diseño moderno.",
    direction: "Cabildo 980",
    category: "hombre",
    sizes: [39, 40, 41, 42, 43, 44],
    colors: ["Negro", "Blanco", "Azul"],
    sellerId: "seller-1",
  },
  {
    id: "11",
    name: "Nike ZoomX Vaporfly",
    price: 599999,
    brand: "nike",
    image: "/images/vaporfly.jpg",
    description: "Zapatilla elite para running competitivo.",
    direction: "Corrientes 2100",
    category: "hombre",
    sizes: [40, 41, 42, 43],
    colors: ["Verde", "Blanco"],
    sellerId: "seller-1",
  },
  {
    id: "12",
    name: "Adidas Superstar",
    price: 299999,
    brand: "adidas",
    image: "/images/superstar.jpg",
    description: "Clásico urbano con puntera de goma.",
    direction: "Florida 320",
    category: "nino",
    sizes: [31, 32 ,33],
    colors: ["Blanco", "Negro"],
    sellerId: "seller-2",
  },
  {
    id: "13",
    name: "Adidas Ultraboost 22",
    price: 529999,
    brand: "adidas",
    image: "/images/ultraboost.jpg",
    description: "Máxima comodidad para running diario.",
    direction: "Belgrano 450",
    category: "hombre",
    sizes: [36, 37, 38, 39, 40],
    colors: ["Negro", "Rosa"],
    sellerId: "seller-2",
  },
  {
    id: "14",
    name: "Adidas Forum Low",
    price: 99999,
    brand: "adidas",
    image: "/images/forum.jpg",
    description: "Streetwear retro estilo básquet.",
    direction: "Caballito 900",
    category: "nino",
    sizes: [29, 30 ,31, 32],
    colors: ["Blanco", "Azul"],
    sellerId: "seller-2",
  },
  {
    id: "15",
    name: "Puma RS-X",
    price: 349999,
    brand: "puma",
    image: "/images/puma-rsx.jpg",
    description: "Diseño chunky moderno.",
    direction: "Recoleta 300",
    category: "mujer",
    sizes: [38, 39, 40, 41, 42],
    colors: ["Blanco", "Negro", "Azul"],
    sellerId: "seller-1",
  },
  {
    id: "16",
    name: "Puma Suede Classic",
    price: 279999,
    brand: "puma",
    image: "/images/puma-suede.jpg",
    description: "Estilo clásico urbano.",
    direction: "San Telmo 120",
    category: "hombre",
    sizes: [39, 40, 41, 42, 43],
    colors: ["Negro", "Rojo"],
    sellerId: "seller-1",
  },
  {
    id: "17",
    name: "Reebok Classic Leather",
    price: 259999,
    brand: "reebok",
    image: "/images/reebok.jpg",
    description: "Retro lifestyle cómodo.",
    direction: "Monserrat 88",
    category: "mujer",
    sizes: [38, 39, 40, 41],
    colors: ["Rosado", "Negro"],
    sellerId: "seller-1",
  },
  {
    id: "18",
    name: "Converse Chuck Taylor",
    price: 199999,
    brand: "converse",
    image: "/images/converse.jpg",
    description: "El clásico de todos los tiempos.",
    direction: "Palermo 500",
    category: "mujer",
    sizes: [36, 37, 38, 39, 40, 41],
    colors: ["Blanco", "Negro"],
    sellerId: "seller-2",
  },
  {
    id: "19",
    name: "Nike Metcon 9",
    price: 399999,
    brand: "nike",
    image: "/images/metcon.jpg",
    description: "Ideal para crossfit y training.",
    direction: "Once 210",
    category: "hombre",
    sizes: [40, 41, 42, 43],
    colors: ["Negro"],
    sellerId: "seller-1",
  },
  {
    id: "20",
    name: "Adidas NMD R1",
    price: 389999,
    brand: "adidas",
    image: "/images/nmd.jpg",
    description: "Streetwear moderno y cómodo.",
    direction: "Belgrano 900",
    category: "nino",
    sizes: [38, 39, 40, 41, 42],
    colors: ["Negro", "Blanco"],
    sellerId: "seller-2",
  },
    {
    id: "21",
    name: "Adidas Supernova",
    price: 289999,
    brand: "adidas",
    image: "/images/supernova.jpg",
    description: " Especiales para trail y running.",
    direction: "Belgrano 970",
    category: "mujer",
    sizes: [38, 39, 40, 41, 42],
    colors: ["Rosado", "Blanco"],
    sellerId: "seller-2",
  },
  {
    id: "22",
    name: "Adizero Evo SL",
    price: 289999,
    brand: "adidas",
    image: "/images/evosl.jpg",
    description: " Especiales para distancias largas.",
    direction: "Moreno 970",
    category: "mujer",
    sizes: [35, 36, 37],
    colors: ["Gris", "Blanco"],
    sellerId: "seller-2",
  },
];


async function main() {
  console.log("Seeding database...");

  for (const seller of SELLERS) {
    await prisma.seller.upsert({
      where: { id: seller.id },
      update: {
        name: seller.name,
        email: seller.email,
        avatarUrl: seller.avatarUrl,
        description: seller.description,
      },
      create: seller,
    });
  }

  for (const product of PRODUCTS) {
    await prisma.product.upsert({
      where: { id: product.id },
      update: {
        name: product.name,
        price: product.price,
        brand: product.brand,
        image: product.image,
        description: product.description,
        category: product.category,
        sizes: product.sizes,
        colors: product.colors,
        sellerId: product.sellerId,
      },
      create: product,
    });
  }

  console.log("Database seeded!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });